### ISSUE TITLE
withtout securityContext - privileged will crash when writing /proc/sys/vm/*

### ISSUE THREAD

**Issue by exherb** [aerospike/aerospike-kubernetes-enterprise#23]
https://github.com/aerospike/aerospike-server/blob/64d890aeda4defbe1796d4f57defa82f02097e4a/cf/src/hardware.c#L2785

I have to patch the statefulset with

```
spec:
  template:
    spec:
      containers:
      - name: aerospike
        securityContext:
          privileged: true
```
